### ISSUE TITLE
Data synchronization between processes

### ISSUE THREAD

**Issue by ceyhunsen** [chainwayxyz/bitcoin-mock-rpc#9]
# Description

Currently, data is stored in memory, for every struct generation. Synchronization is provided using standard Rust tools like `Mutex`, `Cell` and `Arc`. These tools allowed data to be persistent across threads.

After initial synchronization attempts, new issue arrived: Threads need to clone this RPC struct and they fork blockchain from there. This also caused a new synchronization problem across threads. Again, standard Rust tools fixed this issue. `Box` allowed threads to operate on a common memory location.

Although combining all these provided a nice, synchronized, in-memory blockchain, we need more now: Inter-process communication.

## Requirements and Caveats

- We need a copiable or a clonable solution
  - Because we need to move RPC struct between functions
- Why we need to copy or clone RPC struct:
  - We can't open a new RPC connection in every function and except it will only connect target test's blockchain
  - We need to create a new connection and a blockchain in test's start and pass it to the called functions
  - Because we now use a trait implementation, this can also be problematic if we don't pass rpc struct to functions (or maybe not idk)
- We need to be able to store Bitcoin library's structs
  - It is best to store native structs, as is
  - Serializing to string is a bit problematic for some data types, we should avoid it as much as possible

### Use a Database

Databases should provide a consistent state across processes. But there are caveats:

- It is so much work to serialize Rust native structs to database native formats
  - Sometimes it is not possible for some formats
  - If some formats don't support serialization, we need to change ledger structure
  - We can change the structure now but it will also limit what can be added to ledger in the future
- Most of the database libraries are not copiable or clonable
  - Including sqlx and sqlite3 libraries
  - But, wrapping database struct around a Rust synchronization primitive, like `Arc` fixes this (not sure)
- Needs to open a temporary database option
  - SQLite3 has this, no worries
- Some of the database servers provide an `async` interface
  - RpcApi interface is not `async`; Is this a problem?
- They are slower than memory but it is not a biggy
  - We don't need speed in tests
- Depending on a database can be headache for online deployments
  - For example, does Github supports SQLite for it's deployments?

### Implement an Actual RPC Interface

Actually implementing an RPC interface should fix all of our problems. Pro's also comes with caveats, though:

- RPC interface must be designed with copiablity or clonability in mind
- Overhead for tests
  - Creates a server and opens a connection
  - If there are too many tests, OS can cause problems
- Small development time overhead
  - After initial development, it should be a smooth sail though
- In the future, there is a possibility to make this a CLI tool
  - Do anyone cares, though?

### Other Inter-Process Communication Solutions

Please comment if you have something in mind.

**Comment by ekrembal** [comment]
We should use sqlite3

**Comment by kpp** [comment]
Thats a very nicely reported issue. Would you please describe why you need this?

**Comment by ceyhunsen** [comment]
@kpp sorry for the late reply, just saw it.

Clementine creates new processes (or servers in other words) for every new operator and verifier. In a typical integration test, there are 4 verifiers and 1 operator. All these processes/servers need to access our so called Bitcoin blockchain asynchronously. Simple Mutex like solutions would worked if our servers just used threads. But we fork our program to create these servers (there are some other reasons why they are forks, not threads).

So, we need every test to create a new mock Bitcoin blockchain at the start. After process/server creation, this blockchain should not fork it's data. But because there are some Rust related constraints, we call `.clone()` for our RPC struct. And it causes to fork the blockchain and servers have a different blockchains after that. This is the main problem we are facing.

For now, PR #10 is the way to go. Even though serializing/deserializing is a bit hassle. There was another solution: Create an RPC server for every test and let the original Bitcoin RPC library sent it's request directly to this mock RPC server. But it looked like a bit of an over engineering and we went to this way. Although my heart still wants that second approach.

If there are another solutions to this, I would be happy to hear your response.
